Chill\PersonBundle\Entity\AccompanyingPeriod:
    type: entity
    table: person_history_file
    id:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
    fields:
        date_opening:
            type: date
        date_closing:
            type: date
            default: null
            nullable: true
        memo:
            type: text
    manyToOne:
        person:
            targetEntity: Person
            inversedBy: accompanyingPeriods
            cascade: [refresh]
            joinColumn:
                name: person_id
                referencedColumnName: id
        closingMotive:
            targetEntity: Chill\PersonBundle\Entity\AccompanyingPeriod\ClosingMotive
            nullable: true
