Chill\PersonBundle\Entity\AccompanyingPeriod:
    table: accompanying_period
    type: entity
    id:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
    fields:
        openingDate:
            type: date
        closingDate:
            type: date
            default: null
            nullable: true
        remark:
            type: text
    manyToOne:
        person:
            targetEntity: Person
            inversedBy: accompanyingPeriods
            cascade: [refresh]
        closingMotive:
            targetEntity: Chill\PersonBundle\Entity\AccompanyingPeriod\ClosingMotive
            nullable: true
