Chill\PersonBundle\Entity\Person:
    type: entity
    table: null
    repositoryClass: Chill\PersonBundle\Entity\PersonRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        dateOfBirth:
            type: date
            column: date_of_birth
            nullable: true
        placeOfBirth:
            type: string
            length: 255
            column: place_of_birth
            default: ''
        genre:
            type: string
            length: 9
        memo:
            type: text
            default: ''
        email:
            type: text  
        proxyHistoryOpenState:
            type: boolean
            name: proxy_open
        cFData:
            type: array
        phonenumber:
            type:text
    manyToOne:
        countryOfBirth:
            targetEntity: Chill\MainBundle\Entity\Country
            inversedBy: birthsIn
            nullable: true
        nationality:
            targetEntity: Chill\MainBundle\Entity\Country
            inversedBy: nationals
            nullable: true
    oneToMany:
        history:
            targetEntity: PersonHistoryFile
            mappedBy: person
            cascade: [persist, remove, merge, detach]
    lifecycleCallbacks: {  }
