Chill\PersonBundle\Entity\Person:
    type: entity
    table: null
    indexes:
        person_names:
            columns: [firstName, lastName]
    repositoryClass: Chill\PersonBundle\Entity\PersonRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        dateOfBirth:
            type: date
            column: date_of_birth
            nullable: true
        placeOfBirth:
            type: string
            length: 255
            column: place_of_birth
            default: ''
        genre:
            type: string
            length: 9
        memo:
            type: text
            default: ''
        email:
            type: text  
        proxyAccompanyingPeriodOpenState:
            type: boolean
            name: proxy_open
        cFData:
            type: array
        phonenumber:
            type: text
            nullable: true
    manyToOne:
        countryOfBirth:
            targetEntity: Chill\MainBundle\Entity\Country
            inversedBy: birthsIn
            nullable: true
        nationality:
            targetEntity: Chill\MainBundle\Entity\Country
            inversedBy: nationals
            nullable: true
    oneToMany:
        accompanyingPeriods:
            targetEntity: AccompanyingPeriod
            mappedBy: person
            cascade: [persist, remove, merge, detach]
    manyToMany:
        spokenLanguages:
            targetEntity: Chill\MainBundle\Entity\Language
            joinTable:
                name: persons_spoken_languages
                joinColumns:
                    person_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    language_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
