parameters:
#    cl_chill_person.example.class: Chill\PersonBundle\Example

services:   
    chill.person.form.person_creation:
        class: Chill\PersonBundle\Form\PersonType
        arguments:
            - %chill_person.person_fields%
        tags:
            - { name: form.type }
    
    chill.person.accompanying_period_closing_motive:
        class: Chill\PersonBundle\Form\Type\ClosingMotiveType
        scope: request
        arguments:
            - "@request"
        tags:
            - { name: form.type, alias: closing_motive }

    chill.person.search_person:
        class: Chill\PersonBundle\Search\PersonSearch
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@chill.main.security.authorization.helper"
        calls:
            - ['setContainer', ["@service_container"]]
        tags:
            - { name: chill.search, alias: 'person_regular' }
    chill.person.form.type.select2maritalstatus:
        class: Chill\PersonBundle\Form\Type\Select2MaritalStatusType
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: select2_chill_marital_status }
    chill.person.timeline.accompanying_period_opening:
        class: Chill\PersonBundle\Timeline\TimelineAccompanyingPeriodOpening
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: chill.timeline, context: 'person' }

    chill.person.timeline.accompanying_period_closing:
        class: Chill\PersonBundle\Timeline\TimelineAccompanyingPeriodClosing
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: chill.timeline, context: 'person' }

    chill.person.security.authorization.person:
        class: Chill\PersonBundle\Security\Authorization\PersonVoter
        arguments:
            - "@chill.main.security.authorization.helper"
        tags:
            - { name: security.voter }
            - { name: chill.role }
            
    chill.person.birthdate_validation:
        class: Chill\PersonBundle\Validator\Constraints\BirthdateValidator
        arguments:
            - "%chill_person.validation.birtdate_not_before%"
        tags:
            - { name: validator.constraint_validator, alias: birthdate_not_before }
            
    chill.main.form.person_creation:
        class: Chill\PersonBundle\Form\CreationPersonType
        arguments:
            - "@chill.main.form.data_transformer.center_transformer"
        tags:
            - { name: form.type, alias: chill_personbundle_person_creation }
            
    chill.person.form.type.pick_person:
        class: Chill\PersonBundle\Form\Type\PickPersonType
        arguments:
            - "@chill.person.repository.person"
            - "@security.token_storage"
            - "@chill.main.security.authorization.helper"
        tags:
            - { name: form.type }
            
    chill.person.repository.person:
        class: Chill\PersonBundle\Entity\PersonRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'Chill\PersonBundle\Entity\Person'