parameters:
#    cl_chill_person.example.class: Chill\PersonBundle\Example

services:
    chill.person.routing_loader:
        class: Chill\PersonBundle\Routing\RoutesLoader
        tags:
            - { name: routing.loader }
