parameters:
#    cl_chill_person.example.class: Chill\PersonBundle\Example

services:         
    chill.person.accompanying_period_closing_motive:
        class: Chill\PersonBundle\Form\Type\ClosingMotiveType
        scope: request
        arguments:
            - "@request"
        tags:
            - { name: form.type, alias: closing_motive }
            
    chill.person.search_person:
        class: Chill\PersonBundle\Search\PersonSearch
        arguments:
            - "@doctrine.orm.entity_manager"
        calls:
            - ['setContainer', ["@service_container"]]
        tags:
            - { name: chill.search, alias: 'person_regular' }
            
    chill.person.timeline.accompanying_period_opening:
        class: Chill\PersonBundle\Timeline\TimelineAccompanyingPeriodOpening
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: chill.timeline, context: 'person' }
            
    chill.person.timeline.accompanying_period_closing:
        class: Chill\PersonBundle\Timeline\TimelineAccompanyingPeriodClosing
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: chill.timeline, context: 'person' }
