services:
   - chill/database:latest
 
before_script:
   - export GITHUB_COMPOSER_AUTH=$GITHUB_TOKEN
   - composer install --no-interaction
   - cp Tests/Fixtures/App/app/config/parameters.gitlab-ci.yml Tests/Fixtures/App/app/config/parameters.yml
   - php Tests/Fixtures/App/app/console.php --env=test cache:warmup
   - php Tests/Fixtures/App/app/console.php doctrine:migrations:migrate --env=test --no-interaction
   - php Tests/Fixtures/App/app/console.php doctrine:fixtures:load --env=test --no-interaction

test:php-5.6:
   stage: test
   script: phpunit --testdox
test:php-7:
   stage: test
   script: phpunit --testdox
