language: php
php:
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
     - php: hhvm-nightly

sudo: false

addons:
  postgresql: "9.3"

install: 
   - composer install --dev --no-interaction
   - cp Tests/Fixtures/App/app/config/parameters.travis.yml Tests/Fixtures/App/app/config/parameters.yml
  
before_script:
  - psql -c 'create database test0;' -U postgres
  - psql -d test0 -c 'CREATE EXTENSION unaccent;' -U postgres
  - php Tests/Fixtures/App/app/console.php --env=test cache:warmup
  - php Tests/Fixtures/App/app/console.php assets:install Tests/Fixtures/App/web
  - php Tests/Fixtures/App/app/console.php doctrine:migrations:migrate --no-interaction
  - php Tests/Fixtures/App/app/console.php doctrine:fixtures:load --env=test --no-interaction

script: phpunit --coverage-text

notifications:
  email:
     - info@champs-libres.coop
